### PR TITLE
fix(replay): Refactor slot and epoch trackers to heap RwMux pointers

### LINKED ISSUE #983: Panic when accessing root slot's ancestors.
### Description

This line leads to a panic

https://github.com/Syndica/sig/blob/a3250c5546c59e950517ba7ecba74f584617740c/src/consensus/vote_listener.zig#L465

```
0x2c6c876 in processVotesOnce (sig)
                .ancestors = slot_data_provider.getSlotAncestorsPtr(root_slot).?, // must exist for the root slot
                                                                              ^
/home/ubuntu/sig/src/consensus/vote_listener.zig:412:37: 0x2c6e411 in processVotesLoop (sig)
        switch (try processVotesOnce(
                                    ^
/home/ubuntu/.zvm/0.14.1/lib/std/Thread.zig:507:21: 0x2a3b3c2 in callFn__anon_194242 (sig)
                    @call(.auto, f, args) catch |err| {
                    ^
/home/ubuntu/.zvm/0.14.1/lib/std/Thread.zig:757:30: 0x29703c4 in entryFn (sig)
                return callFn(f, args_ptr.*);
                             ^
???:?:?: 0x730fde29caa3 in ??? (libc.so.6)
Unwind information for `libc.so.6:0x730fde29caa3` was not available, trace may be incomplete
```

### How to Reproduce the Bug

Run offline replay with consensus enabled on test net

`sig replay-offline -c testnet --replay-threads 1 --disable-consensus=false  --use-disk-index --skip-snapshot-validation`

After a while, the panic should pop up.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dadepo**
Fixes #983

Ran this for couple of hours and confirmed certain checkpoints suggesting everything chugs along all fine:

```
time=2025-10-08T15:45:34.050Z level=info scope=replay_tower message="voting: 361995647 0.0%"
time=2025-10-08T15:45:35.216Z level=info scope=fork_choice message="fork_choice: new root set to slot=361995616 hash=36QFWceZSMAmffRPmvzEQ8z5NuEJrFdEPZmZEqHCzrNT"
```

and previously with explicit `std.debug.print` debug-ing confirming the pruning seems to be working fine

```
pruneNonRooted start: root=361996357, tracked_slots_before=35
SlotTracker.pruneNonRooted: removing slot 361996356 (< root 361996357)
```

### CODE REVIEW

File: src/consensus/vote_listener.zig [hunk 1]
```diff
@@ -934,7 +934,7 @@ fn trackNewVotesAndNotifyConfirmations(
 
             const maybe_hash: ?Hash = get_hash: {
                 if (slot == last_vote_slot) break :get_hash last_vote_hash;
-                break :get_hash slot_data_provider.getSlotHash(last_vote_slot);
+                break :get_hash slot_data_provider.getSlotHash(slot);
```
Comment (dadepo) [inline src/consensus/vote_listener.zig:933]: This fixed the panic:

```
.slot_status = replay.consensus.edge_cases.SlotStatus{ .frozen = 4SqH29ss9JVmkPg7rNFwLMJdz5HLgf22tanfAWcHhQMv } }"
thread 20960 panic: Additional duplicate confirmed notification for slot 361995285 with a different hash
/home/ubuntu/sig/src/replay/consensus/edge_cases.zig:571:32: 0x30cd778 in processDuplicateConfirmedSlots (sig)
                std.debug.panic(
                               ^
/home/ubuntu/sig/src/replay/consensus/edge_cases.zig:74:39: 0x30d0cca in processEdgeCases (sig)
```

Comment (InKryption) [reply src/consensus/vote_listener.zig:933]: Good spot, it can hold that `slot != last_vote_slot` if `accumulate_intermediate_votes`.
