### PR TITLE
fix(consensus): Remove null unwrapping in processDuplicateConfirmedSlots

### LINKED ISSUE #1057: fix(consensus): null unwrap
```
validator -c testnet --use-disk-index --skip-snapshot-validation --max-shreds 100100100
```

this stack trace points to the wrong place, but it's the signature of this bug that i keep observing. the problem is probably somewhere in processClusterSync, but i don't know exactly
```
Nov 05 17:20:19 ip-172-31-43-92 sig[13432]: time=2025-11-05T17:20:19.596Z level=error scope=panic message="attempt to use null value"
Nov 05 17:20:19 ip-172-31-43-92 sig[13432]: thread 13826 panic: attempt to use null value
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: /usr/local/bin/lib/std/io/Writer.zig:19:38: 0x2056956 in processClusterSync (sig)
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:         index += try self.write(bytes[index..]);
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:                                      ^
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: /home/sig/sig/src/replay/consensus/core.zig:376:36: 0x206f433 in process (sig)
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:                 .processClusterSync(allocator, .from(self.logger), .{
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:                                    ^
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: /home/sig/sig/src/replay/service.zig:117:34: 0x208b5bd in advance (sig)
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:             try consensus.process(
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:                                  ^
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: /home/sig/sig/src/utils/service.zig:172:9: 0x1e57661 in entryFn (sig)
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:         const result = @call(.auto, function, args);
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]:         ^
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: ???:?:?: 0x765856c9caa3 in ??? (libc.so.6)
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: Unwind information for `libc.so.6:0x765856c9caa3` was not available, trace may be incomplete
Nov 05 17:20:20 ip-172-31-43-92 sig[13432]: ???:?:?: 0x765856d29c6b in ??? (libc.so.6)
```

### PR DESCRIPTION
**Pull request by dadepo**
Fixes #1057

### CODE REVIEW

File: src/replay/consensus/cluster_sync.zig [hunk 1]
```diff
@@ -584,7 +584,23 @@ fn processDuplicateConfirmedSlots(
...
+                    else
+                        0;
+
+                    logger
+                        .debug()
+                        .logf(
+                        \\ duplicate confirmed slot not found in tracker: root={}, highest_tracked_slot={}, confirmed_slot={}
+                    ,
+                        .{ root, highest_slot, confirmed_slot },
+                    );
```
Comment (dnut) [inline src/replay/consensus/cluster_sync.zig]: I don't think we need to add extra computation, complexity, and coupling with the slot tracker, just to log a message about a very normal situation that will happen very often. I think `else null` is fine here.

Comment (dadepo) [reply src/replay/consensus/cluster_sync.zig]: Reverted [d405c9d](https://github.com/Syndica/sig/pull/1068/commits/d405c9da39de0d95fdc643e639b368f1a098f9ae)

**Review by InKryption — APPROVED** [review]
