### PR TITLE
fix(accountsdb): get snapshot validation working again / use delta LT hash

### LINKED ISSUE #988: fix(accountsdb): snapshot validation
currently snapshot validation fails and we need to always skip it.

### PR DESCRIPTION
**Pull request by Sobeston**
closes #988

changes
- uses the delta_lt hash instead of the old hash
- brings us more up to date with snapshots generated from a recent agave version
- removes incremental capitalisation checking (it seems dead in agave, and pointless)

### CODE REVIEW

**Review by Rexicon226 — APPROVED** [review]

File: src/accountsdb/db.zig [hunk 1]
```diff
@@ -1354,179 +1327,146 @@ pub const AccountsDB = struct {
...
+                    total_lamports += account.lamports;
+
+                    if (max_slot_ref.slot == 0) continue;
+                    break :slot max_slot_ref.slot;
+                };
+
+                // "mix out" old version of account from hash
+                {
+                    // I expect this branch to not be taken for full snapshots, however it would
+                    // still be entirely legal.
```
Comment (dnut) [inline src/accountsdb/db.zig]: This is not correct if you're calculating an lthash over the entire database from scratch. The lthash of the database can be calculated by mixing every account's hash into identity. Mixing out old versions from that will result in an incorect lthash.

File: src/accountsdb/db.zig [hunk 2]
```diff
@@ -1354,179 +1327,146 @@ pub const AccountsDB = struct {
...
+                    const previous_slot_ref = slotListMaxWithinBounds(
+                        ref_head.ref_ptr,
+                        null,
+                        latest_slot - 1,
+                    ) orelse continue;
+
+                    const account = try self.getAccountFromRef(allocator, previous_slot_ref);
+                    defer account.deinit(allocator);
+
+                    mix_out.mixIn(account.ltHash(previous_slot_ref.pubkey));
```
Comment (dnut) [inline src/accountsdb/db.zig]: Why not `lt_hash.mixOut`? the `mix_out` variable seems unnecessary.

File: src/accountsdb/db.zig (hunk 1 above)
Comment (Sobeston) [reply src/accountsdb/db.zig]: I believe the lthash should be a hash of all *accounts* at the slot we're concerned with, not all entries for each account.

Any entry for an account which has a later entry can be considered overwritten - if a snapshot contains old entries I think this is legal but basically junk data

File: src/accountsdb/db.zig (hunk 2 above)
Comment (Sobeston) [reply src/accountsdb/db.zig]: https://github.com/Syndica/sig/pull/993/commits/bf8250e6d704848a6cf5ffb04a743b6a782a809a

Think I followed agave here, removed it, we don't need it

File: src/accountsdb/db.zig (hunk 1 above)
Comment (dnut) [reply src/accountsdb/db.zig]: > I believe the lthash should be a hash of all accounts at the slot we're concerned with, not all entries for each account.

Yes, we're on the same page here.

> if a snapshot contains old entries I think this is legal but basically junk data

It's junk data that should be totally ignored, not mixed out.

Let's say all of accountsdb has only a single account called `a`. In all of history, there have been only two versions of the account: `a0` and `a1`. The lt hash for accountsdb is `hash(a1)`. But here it seems like you're calculating the lt hash as `hash(a1) - hash(a0)`.

This makes sense when you're calculating an incremental hash from an incremental snapshot because you plan to immediately sum it with the hash from the full snapshot, which is `hash(a0)`, so the sum gives you `hash(a1)`. But if you're using this function to calculate the hash for all of accountsdb in one shot, `hash(a1) - hash(a0)` will be your final value, which is not correct.

Am I missing something about the context where this function is used?

Comment (Sobeston) [reply src/accountsdb/db.zig]: Addressed in a1b8342900ba77712cf2d3ac395278c7c95620e5

File: src/accountsdb/db.zig [hunk 3]
```diff
@@ -1081,16 +1071,29 @@ pub const AccountsDB = struct {
...
         },
+
+        fn min_slot(self: AccountHashesConfig) ?Slot {
+            return switch (self) {
+                .FullAccountHash => null,
+                .IncrementalAccountHash => |iac| iac.min_slot,
+            };
+        }
+
+        fn max_slot(self: AccountHashesConfig) ?Slot {
```
Comment (InKryption) [inline src/accountsdb/db.zig]: Naming convention here should probably still be camelCase.

File: src/accountsdb/db.zig [hunk 4]
```diff
@@ -1122,57 +1125,50 @@ pub const AccountsDB = struct {
...
+            var hash: LtHash = .IDENTITY;
+            for (task_results) |result| {
+                lamports_sum += result.lamports;
+                hash.mixIn(result.hash);
+            }
+            break :blk .{ lamports_sum, hash };
+        };
+
+        for (task_results) |result| {
+            total_lamports -|= result.subtract;
```
Comment (InKryption) [inline src/accountsdb/db.zig]: Any reason not to do this subtraction alongside the addition?

Comment (Sobeston) [reply src/accountsdb/db.zig]: It's possible for a shard to end with result.subtract > result.lamports. Unlikely to happen with real data? But I do this to avoid the possibility of overflow

File: src/accountsdb/db.zig (hunk 3 above)
Comment (Sobeston) [reply src/accountsdb/db.zig]: True, 18be3cb9b1b8f6d1cf48dffde2cd30981040b726

File: src/accountsdb/db.zig (hunk 4 above)
Comment (InKryption) [reply src/accountsdb/db.zig]: Moreso asking why this isn't
```suggestion
            for (task_results) |result| {
                total_lamports -|= result.subtract;
                lamports_sum += result.lamports;
                hash.mixIn(result.hash);
            }
            break :blk .{ lamports_sum, hash };
        };
```

**Review by InKryption — APPROVED** [review]

**Review by InKryption — APPROVED** [review]

**Review by dnut — APPROVED** [review]
